add hanasa sub domain
fransallen/thedev.id pull request #394
Opened 2022-06-17 03:04 UTC by nnivxix

2022-06-17 04:10 UTC, nnivxix commented
many people still misspelling my name, **"ha na sa"** not ~~"ha sa na"~~. Hahaha

2022-06-17 04:44 UTC, fransallen commented
Before I merge this PR. Please:
1. Edit `hanasa.vercel.app/` to `hanasa.vercel.app`.
2. Run `npm run sort` to sort json.

2022-06-17 04:50 UTC, fransallen commented
> many people still misspelling my name, "ha na sa" not "ha sa na"

Kalau "hosanna" nanti malah pada nyanyi lagu rohani mas. Sorry for joke :D

2022-06-17 05:48 UTC, nnivxix commented
> Before I merge this PR. Please:
> 
> 1. Edit `hanasa.vercel.app/` to `hanasa.vercel.app`.
> 2. Run `npm run sort` to sort json.

done

2022-06-17 06:30 UTC, fransallen requested changes

2022-06-17 06:30 UTC, fransallen commented on subdomains.json
> +  "hanasa": "hanasa.vercel.app/",
Can you remove the trailing slash?

2022-06-17 07:01 UTC, nnivxix commented on subdomains.json
> +  "hanasa": "hanasa.vercel.app/",
yeah, I'am

2022-06-18 00:43 UTC, merged

2022-06-18 00:44 UTC, fransallen commented
Merged :confetti_ball: